"""Add auto reply fields

Revision ID: 1d168cabae21
Revises: 1ab31e471786
Create Date: 2026-09-22 22:10:53.710682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d168cabae21'
down_revision = '1ab31e471786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auto_reply', sa.Boolean(), nullable=False))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auto_reply', sa.Boolean(), nullable=False))

    with op.batch_alter_table('translator_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_reply_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_reply_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_reply_cooldown_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translator_preference', schema=None) as batch_op:
        batch_op.drop_column('auto_reply_cooldown_hours')
        batch_op.drop_column('auto_reply_message')
        batch_op.drop_column('auto_reply_enabled')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_auto_reply')

    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('is_auto_reply')

    # ### end Alembic commands ###
